[package]
name = "day-19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
glam = "0.24.2"
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"
