[package]
name = "day-18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
glam = "0.24.1"
itertools = "0.11.0"
nom = "7.1.3"
rayon = "1.7.0"
